#!/bin/bash

set -u
set -e

dir=""

cleanup() {
    [ -d "$dir" ] && rm -rf "$dir"
}

trap cleanup EXIT

dir="$(mktemp -d)"

cd "$dir"
cat > "$dir/meta-data" <<EOF
instance-id: iid-thip-$(date +%s)
local-hostname: thip
EOF

cat > "$dir/user-data" <<EOF
#cloud-config
password: test
ssh_pwauth: False
#chpasswd: { expire: False }

ssh_authorized_keys:
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINuRT02EgmvQdI96X/qGdUCCSUbTHlvRiHuF0BKpNhch igor@localhost.localdomain

write_files:
- path: /etc/sysconfig/network
  permissions: '0644'
  content: |
    NETWORKING=yes

- path: /etc/sysconfig/network-scripts/ifcfg-eth0
  permissions: '0644'
  content: |
    DEVICE=eth0
    IPADDR=192.168.100.3
    NETMASK=255.255.255.0
    GATEWAY=192.168.100.1
    ONBOOT=yes

- path: /etc/resolv.conf
  permissions: '0644'
  content: |
    nameserver 192.168.100.1

- path: /etc/test
  permissions: '0644'
  content: |
    Hello!

bootcmd:
 - ifdown eth0
 - ifup eth0  
 - sed -i 's/^#\?\s*UseDNS\>.*/UseDNS no/' /etc/ssh/sshd_config 
 - echo BOOT '**************************************************'
 - 'cat /etc/test || true'
runcmd:
 - echo RUN '**************************************************'
 - 'cat /etc/test || true'
EOF

cat user-data

genisoimage -output /var/lib/libvirt/images/atomic_init.iso \
	    -volid cidata -joliet -rock -input-charset utf8 \
	    user-data meta-data
