#!/bin/bash

set -u -e

cmd_log() {
    echo "$*" 1>&2
    "$@"
}

if [[ "$(scutil --get HostName 2>/dev/null || true)" != miranda-mac ]]; then
    cmd_log scutil --set HostName miranda-mac   
fi

# No automatic sleep even on battery plus disable standby as it often
# leads to unexpecte shutdown, not hybernation.
cmd_log pmset -a sleep 0 hibernatemode 3 destroyfvkeyonstandby 1 standby 0 standbydelay 10800 \
    womp 0 ttyskeepawake 0 autopoweroff 0
