#!/bin/sh
patch_name="$(hg branch).patch"
if test $? -gt 1; then
    exit 1
fi

extra_opts=""
if test $? -gt 0; then
    if test "$1" = "-b"; then
	extra_opts=" $1"
    else
	exit 1
    fi
fi 

file="$HOME/s/$patch_name"
hg diff -p -U9 -r default $extra_opts > "$file"
l "$file"
echo "$file"
