#!/bin/sh

base=`basename "$0"`
cmd=grep
if [ "$base" = fgreptree ]; then
  cmd=fgrep
elif [ "$base" = egreptree ]; then
  cmd=egrep
fi

exec u-find . -follow \
  -type f -not -name '.#*' -not -name '*~' -not -name '*.orig' -print0 \
  | xargs -0 "$cmd" "$@"

