#!/bin/bash

# send-to-untrusted

ssh_script='
set -e -u
text="$(base64 -w0)"
(printf %s "$text" | base64 -d | xclip -d :0.0 -selection clipboard -i) \
    < /dev/null > /dev/null 2> /dev/null &
disown -a
'

xclip -o | ssh user@untrusted "$ssh_script"
