#!/bin/bash

root=/var/chroot/i386
if test ! -d "$root"; then
  echo "Location of $root is unknown" 1>&2
  exit 1
fi

libs32="$root/lib:$root/usr/lib"
if test "${LD_LIBRARY_PATH/$libs32}" = "$LD_LIBRARY_PATH"; then
  # LD_LIBRARY_PATH does not contain libs32
  export LD_LIBRARY_PATH="${LD_LIBRARY_PATH+${LD_LIBRARY_PATH}:}$libs32"
fi

if test $# -eq 0; then
  exec $SHELL
fi

exec "$@"
