#!/bin/sh

while test "$1" = "-c"; do 
    test $# -ge 2 || (echo "Missing ssh key argument" 1>&2; exit 1)
    ssh-add "$2" > /dev/null 2>&1 || ( echo "failed ssh-add" 1>&2; exit 1 )
    shift 2
done

test $# -ge 1 || ( echo "Missing ssh exec argument" 1>&2; exit 1 )

exec "$@"
