#!/bin/bash

if test "$1" != man; then 
  echo "Wrong usage: the first argument should be man" 1>&2
  exit 1
fi
shift

name_prefix="$1"
shift

if test -z "$name_prefix"; then 
  exit 0
fi

section="$1"
shift

if test "$section" == "man" -o -z "$section"; then
  section="?*"
fi

IFS=':'
manpath=( $(manpath) )
unset IFS
shopt -s nullglob
for man_dir in "${manpath[@]}"; do
  dir_entries=( $man_dir/man${section}/${name_prefix}*.?* )
  if test ${#dir_entries[@]} -gt 0 ; then
    # remove everything before last slash
    dir_entries=( ${dir_entries[@]##*/} )
    # remove possible .gz
    dir_entries=( "${dir_entries[@]%.gz}" )
    # remove .section suffix
    dir_entries=( "${dir_entries[@]%.?*}" )
    IFS=$'\n'
    echo "${dir_entries[*]}"
    unset IFS
  fi
done