#!/bin/sh

freq=2400000
for i in /sys/devices/system/cpu/cpu?/cpufreq/scaling_governor ; do
  echo performance > $i
# echo userspace > $i
done

#for i in /sys/devices/system/cpu/cpu?/cpufreq/scaling_setspeed ; do
#  echo $freq > $i
#done
