#!/bin/bash

exec xmodmap                    \
    -e 'clear Mod1'             \
    -e 'clear Mod3'             \
    -e 'clear Mod4'             \
    -e 'add Mod1 = Alt_L'       \
    -e 'remove shift = Shift_R' \
    -e 'add Mod3 = Shift_R'

