#!/bin/sh

dir="/scratch/igor/hippy.ru"
mkdir -p "$dir/files"
old_backup="$dir/$(date --date='-20 days' --rfc-3339=date)"
rm -rf "$old_backup"
backup="$dir/$(date --rfc-3339=date)"

(
#rsync -a --no-D --partial -v --delete --backup --backup-dir="$backup" \
#  --exclude=/public_html/cgi-bin/karta \
#  -e "ssh -i $dir/hippy_ru" \
#  hippyru@hippy.ru:'public_html suspect script include' "$dir/files"

rsync -a --no-D --partial -v --delete --backup --backup-dir="$backup" \
   --rsh='ssh -i /scratch/igor/hippy.ru/ssh/hippyru_backup -l hippyru-backup -W 127.0.0.1:873' \
   rsync://hippyru.net/www/ "$dir/www"

cd "$dir/ljdump"

echo "Backing up lubava.livejournal.com"
python ljdump.py

) > $dir/backup_status.txt 2>&1
