#!/bin/bash

set -u

err() {
    printf 'Error: %s\n' "$*" 1>&2
    exit 1
}

usage_err() {
    if [[ $# -ge 1 ]]; then
	printf '%s\n' "$*" 1>&2
    fi
    printf "Usage: $0 [-n] LOCATION\n" 1>&2
    exit 1
}


has_ip() {
    local dns_name="$1"
    local ip="$2"
    test "$ip" = "$(dig +short "$dns_name" A)"
}

has_dns() {
    local dns_ip="$1" word ip
    {
	while read word ip; do
	    if [[ "$word" == "nameserver" && "$ip" == "$dns_ip" ]]; then
		return 0;
	    fi
	done;
    } < /etc/resolv.conf 
    return 1
}

location=""
negate=""

while getopts n opt; do
    case "$opt" in
	n ) negate=1 ;;
	* ) usage_err;;
    esac
done
shift $(($OPTIND - 1))

[[ $# -ge 1 ]] || usage_err "missing location argument"
location="$1"
[[ $# -eq 1 ]] || usage_err "unexpected argument after location"

code=1
case "$location" in
    home ) has_dns 192.168.2.1 && code=0 ;;
    runit ) has_ip watson.runitsoft.com 10.0.0.14 && code=0 ;;
    * ) echo "unknown location - '$1'" 1>&2 ;;
esac

if [[ -n "$negate" ]]; then
    let code=1-$code
fi

exit $code
