#!/bin/bash

mosh_options=()

while test $# -ne 0 && test "x${1#-}" != "x$1" ; do
    mosh_options+=("$1")
    shift
done


port=0
if test $# -ne 0; then
    host="$1"
    shift
    case "$host" in
	rwww )
	    host="root@www.runitsoft.com"
	    ;;
	watson )
	    host=watson.runitsoft.com
	    port=35196
	    ;;
	dserver )
	    host=dserver.mir2.org
	    port=18284
	    ;;
	thip )
	    host=test.hippyru.net
	    port=32025
	    ;;
    esac
    mosh_options+=("$host")
fi

test $port -gt 0 && mosh_options+=(--port $port)

export MOSH_TITLE_NOPREFIX=1
exec mosh "${mosh_options[@]}" "$@"
