#!/bin/bash

#geometry=1280x760
geometry=1016x536
dpi=135
port=3

#exe="/opt/TigerVNC/bin/vncserver"
args=()

#if test ! -x "$exe"; then
    exe="$(which tightvncserver 2>/dev/null)"
    exe=""
    if test -n "$exe"; then
	args+=(-compatiblekbd)
    else
	exe="$(which vncserver 2>/dev/null)"
	test -z "$exe" && { echo "Cannot find vncserver executable." 1>&2; exit 1;}
    fi
#fi

args+=(-localhost -geometry "$geometry" -depth 8 -dpi "$dpi" )

exec env -i \
  "HOME=$HOME" "USER=$USER" "SHELL=$SHELL" "HOSTNAME=$HOSTNAME" "PATH=$PATH"\
  "${exe[@]}" :$port "${args[@]}"
