#!/bin/bash
screen -q -ls
status=$?
case $status in
    10 | 11 ) new_session="" ;;
    9 | 8 )   new_session="1" ;;
    * )
	echo "Unexpected exit status of screen -q -ls: $status" 1>&2
	sleep 60
	exit 1
	;;
esac

if test -n "$SSH_AUTH_SOCK"; then
    agent_link="$HOME/.ssh/screen_ssh_agent";
    rm -f "$agent_link"
    ln -s "$SSH_AUTH_SOCK" "$agent_link"
    export SSH_AUTH_SOCK="$agent_link"
fi

if test -n "$new_session"; then
    # Remove unwanted variables
    exec env \
      -u SSH_CLIENT -u SSH_CONNECTION -u SSH_TTY \
      screen -m emacs -nw
fi
  
exec screen -D -r
