#!/bin/bash 

# Disable touchpad taps for one second after typing. For this to work
# make sure that something like the following is in /etc/X11/xorg.conf
#
#   Section "InputDevice"
#         Identifier "touchpad"
#         Driver "synaptics"
#         Option "SHMConfig"   "true"
#         Option "CorePointer"
#   EndSection

# With my qubes setup this convience is not possible.

#~/a/gnome/libcopies/gnome/gnome-encfs -m

syndaemon -d -t -i 1

case "$DESKTOP_SESSION" in
    xfce ) gnome-sound-applet & ;;
    gnome ) gsettings set org.gnome.desktop.interface enable-animations false ;;
esac

u-start-emacs &
