#!/bin/bash -l

# This script is invoked as a login shell to get bashrc.dot customizations

args=(--no-splash -bg '#F8F8FF' -fg '#000000')

case "${DESKTOP_SESSION,,}" in
    gnome | xfce ) args+=(--fullscreen) ;;
    * ) args+=(--maximized) ;;
esac

exec emacs "${args[@]}"
