#!/bin/bash

# Uncomment the following two lines for normal desktop:
unset SESSION_MANAGER
#exec /usr/bin/gnome-session


u-fix-vnc-xmodmap

#exec /usr/bin/gnome-session
exec /usr/bin/xfce4-session



#u-term &
#exec /usr/bin/xfdesktop

#u-term &
#xmonad

#u-term

#/usr/bin/xterm &

#exec /usr/bin/xmonad
#exec /usr/bin/lxsession
#exec /usr/bin/xfdesktop
#exec /usr/bin/xterm

#exec $HOME/bin/u-term
#[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
#[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
#xsetroot -solid grey
#vncconfig -iconic &
#xterm -geometry 80x24+10+10 -ls -title "$VNCDESKTOP Desktop" &
#twm &
