#!/bin/sh
read host port
if test "$port" -eq 22; then
    case "$host" in
      watson | ar | f2 )
        port=22
	if grep -q intranet.runitsoft.com /etc/resolv.conf ; then
	    test "$host" = f2 && host=10.0.0.42
        elif grep -q Sandslimarka55.dnbnor.lan /etc/resolv.conf ; then
            # Connect through the proxy
            exec nc --proxy-type http --proxy 10.20.16.28:88 watson.runitsoft.com 443
	else
	    test "$host" = f2 && port=20022
	    host=watson.runitsoft.com
	fi
	;;
      dserver )
        host=192.168.1.10
        ;;
      ds )
        host=192.168.1.9
        ;;
    esac
fi
exec /usr/bin/nc "$host" "$port"
